apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2017-07-02T05:15:09Z
    name: default-http-backend
    namespace: nginx-ingress
    resourceVersion: "956052"
    selfLink: /api/v1/namespaces/nginx-ingress/services/default-http-backend
    uid: 6b3c6b64-5ee5-11e7-a6f7-42010a8000ed
  spec:
    clusterIP: 10.11.243.147
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: default-http-backend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.beta.kubernetes.io/external-traffic: OnlyLocal
      service.beta.kubernetes.io/healthcheck-nodeport: "30598"
    creationTimestamp: 2017-07-02T05:52:55Z
    labels:
      app: nginx-ingress-lb
    name: nginx-ingress-lb
    namespace: nginx-ingress
    resourceVersion: "959604"
    selfLink: /api/v1/namespaces/nginx-ingress/services/nginx-ingress-lb
    uid: b1ade42a-5eea-11e7-a6f7-42010a8000ed
  spec:
    clusterIP: 10.11.254.108
    externalTrafficPolicy: Cluster
    loadBalancerIP: 130.211.177.23
    ports:
    - name: http
      nodePort: 31544
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      nodePort: 32546
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      k8s-app: nginx-ingress-controller
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 130.211.177.23
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
